### ISSUE TITLE
Local time details not calculated at 00:00

### ISSUE THREAD

**Issue by sarahcd** [movestore/Convert-Times#1]
At 00:00 local time, all of the local time components are returned as NA. They should all be calculated based on the calendar day in the timestamp and time 0:00:00.

<img width="672" alt="image" src="https://user-images.githubusercontent.com/15783614/206267122-9ed2400d-877b-4e60-b247-4f912f31220b.png">

**Comment by andreakoelzsch** [comment]
Indeed, you are right, this seems to be an edge case bug that I have not considered, will work on it.

**Comment by andreakoelzsch** [comment]
There was some data type inconsistency that I have fixed now. Update should be available on MoveApps in an hour or so
