### ISSUE TITLE
sunrise/sunset based on UTC day

### ISSUE THREAD

**Issue by sarahcd** [movestore/Convert-Times#2]
It seems that the sunrise and sunset are based on the day according to the UTC date rather than the local date.
This means, for example, that in UTC-8, after 16:00 local time, the reported sunrise/sunset are those for the next (local) day. In the example below, for 3 April 16:00 local time I am given the sunrise as 4 April 7:41 local and sunset at 4 April 21:15 local.

I'm not sure of the expected behavior. Intuitively, I would assume that the sunrise and sunset are either
* the sunrise and sunset of the local calendar day
* or possibly, the sunrise and sunset in between which the local timestamp falls

<img width="525" alt="image" src="https://user-images.githubusercontent.com/15783614/206273337-4070a269-f1f5-4530-9f80-a8ffe813c464.png">

**Comment by andreakoelzsch** [comment]
Hi Sarah, indeed sunrise and sunset are in UTC here (and in all my Apps that have this). Regarding which sunset/sunrise to put, I have gone through some comparisons to make sure that your option 2 is met, i.e. that the location's timestamp is between the sunrise and sunset (or sunset and sunrise if at night). I would really leave it like that, of course, I can rename the columns to "sunrise_timestamps_utc" and "sunset_timestamp_utc". However, my logic was that anything that is not specified (like "_local") is automatically UTC... What do you think?
